var DISQUS=function(c){var f={AssertionError:function(a){this.message=a}};f.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};f.assert=function(a,d){if(!a)throw new f.AssertionError(d);};var d=[];f.define=function(a,g){typeof a==="function"&&(g=a,a="");for(var h=a.split("."),b=h.shift(),e=f,n=(g||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},c);b;)e=e[b]?e[b]:e[b]={},b=h.shift();for(var k in n)n.hasOwnProperty(k)&&
(n.__overwrites__||e[k]!==null&&f.assert(!e.hasOwnProperty(k),"Unsafe attempt to redefine existing module with "+k),e[k]=n[k],d.push(function(a,h){return function(){delete a[h]}}(e,k)));return e};f.use=function(a){return f.define(a)};f.cleanup=function(){for(var a=0;a<d.length;a++)d[a]()};return f}(this);
DISQUS.define(function(c,f){var d=c.document,a=d.getElementsByTagName("head")[0]||d.body,g={running:!1,timer:null,queue:[]};DISQUS.defer=function(a,b){function e(){var a=g.queue;if(a.length===0)g.running=!1,clearInterval(g.timer);for(var h=0,b;b=a[h];h++)b[0]()&&(a.splice(h--,1),b[1]())}g.queue.push([a,b]);e();if(!g.running)g.running=!0,g.timer=setInterval(e,100)};DISQUS.each=function(a,b){var e=a.length,d=Array.prototype.forEach;if(isNaN(e))for(var g in a)a.hasOwnProperty(g)&&b(a[g],g,a);else if(d)d.call(a,
b);else for(d=0;d<e;d++)b(a[d],d,a)};DISQUS.extend=function(a){DISQUS.each(Array.prototype.slice.call(arguments,1),function(b){for(var e in b)a[e]=b[e]});return a};DISQUS.serializeArgs=function(a){var b=[];DISQUS.each(a,function(a,h){a!==f&&b.push(h+(a!==null?"="+encodeURIComponent(a):""))});return b.join("&")};DISQUS.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};DISQUS.serialize=function(a,b,e){b&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=DISQUS.serializeArgs(b));
if(e)return b={},b[(new Date).getTime()]=null,DISQUS.serialize(a,b);b=a.length;return a.charAt(b-1)=="&"?a.slice(0,b-1):a};DISQUS.require=function(h,b,e,g,f){function c(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))g&&g(),l&&clearTimeout(l),DISQUS.bean.remove(a.target,p,c)}var i=d.createElement("script"),p=i.addEventListener?"load":"readystatechange",l=null;i.src=DISQUS.serialize(h,b,e);i.async=!0;i.charset="UTF-8";(g||f)&&DISQUS.bean.add(i,p,c);f&&(l=setTimeout(function(){f()},
2E4));a.appendChild(i);return DISQUS};DISQUS.requireStylesheet=function(g,b,e){var f=d.createElement("link");f.rel="stylesheet";f.type="text/css";f.href=DISQUS.serialize(g,b,e);a.appendChild(f);return DISQUS};DISQUS.requireSet=function(a,b,e){var d=a.length;DISQUS.each(a,function(a){DISQUS.require(a,{},b,function(){--d===0&&e()})})};DISQUS.injectCss=function(g){var b=d.createElement("style");b.setAttribute("type","text/css");g=g.replace(/\}/g,"}\n");c.location.href.match(/^https/)&&(g=g.replace(/http:\/\//g,
"https://"));b.styleSheet?b.styleSheet.cssText=g:b.appendChild(d.createTextNode(g));a.appendChild(b)}});
DISQUS.define("JSON",function(){function c(a){return a<10?"0"+a:a}function f(a){b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var b=k[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var c,h,i,k,l=e,m,j=b[a];j&&typeof j==="object"&&typeof j.toJSON==="function"&&!g&&(j=j.toJSON(a));typeof o==="function"&&(j=o.call(b,a,j));switch(typeof j){case "string":return f(j);case "number":return isFinite(j)?String(j):"null";case "boolean":case "null":return String(j);
case "object":if(!j)return"null";e+=n;m=[];if(Object.prototype.toString.apply(j)==="[object Array]"){k=j.length;for(c=0;c<k;c+=1)m[c]=d(c,j)||"null";i=m.length===0?"[]":e?"[\n"+e+m.join(",\n"+e)+"\n"+l+"]":"["+m.join(",")+"]";e=l;return i}if(o&&typeof o==="object"){k=o.length;for(c=0;c<k;c+=1)h=o[c],typeof h==="string"&&(i=d(h,j))&&m.push(f(h)+(e?": ":":")+i)}else for(h in j)Object.hasOwnProperty.call(j,h)&&(i=d(h,j))&&m.push(f(h)+(e?": ":":")+i);i=m.length===0?"{}":e?"{\n"+e+m.join(",\n"+e)+"\n"+
l+"}":"{"+m.join(",")+"}";e=l;return i}}var a={},g=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,n,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;a.stringify=function(a,b,g){var f;n=e="";if(typeof g==="number")for(f=0;f<g;f+=1)n+=" ";else typeof g==="string"&&(n=g);if((o=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return d("",{"":a})};a.parse=function(a,b){function g(a,
e){var d,f,c=a[e];if(c&&typeof c==="object")for(d in c)Object.hasOwnProperty.call(c,d)&&(f=g(c,d),f!==void 0?c[d]=f:delete c[d]);return b.call(a,e,c)}var e,a=String(a);h.lastIndex=0;h.test(a)&&(a=a.replace(h,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),
typeof b==="function"?g({"":e},""):e;throw new SyntaxError("JSON.parse");};var i={a:[1,2,3]},p,l;if(Object.toJSON&&Object.toJSON(i).replace(/\s/g,"")==='{"a":[1,2,3]}')p=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(i='{"a":[1,2,3]}'.evalJSON(),i.a&&i.a.length===3&&i.a[2]===3&&(l=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),g=!(a&&a.length===3&&a[2]===3))})();if(g||!p||!l)return{stringify:a.stringify,parse:a.parse};return{stringify:p,
parse:l}});
DISQUS.define("Bus",function(){function c(a){a=a.split("/");return a[0]+"//"+a[2]}var f=DISQUS.use("JSON"),d=window.location.hash.slice(1),a=window.parent,g=document.referrer,h={};h.client=c(document.location.href);h.host=g?c(g):h.client;return{origins:h,postMessage:function(b){b.sender=d;b=f.stringify(b);a.postMessage(b,h.host)},sendHostMessage:function(a,e){e=e||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:e})},sendGlobalMessage:function(a,e){e=e||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:e})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var c=window.addEventListener?window.addEventListener:window.attachEvent,f=window.addEventListener?"message":"onmessage";if(!c)throw Error("No event support.");c(f,function(d){var a=DISQUS.Bus,g=d.origin;if(!(g!=a.origins.client&&g!=a.origins.host)){var c;try{c=DISQUS.JSON.parse(d.data)}catch(b){return}d=c.data;switch(c.scope){case "client":a.trigger(d.eventName,d.data)}}},!1)});
DISQUS.define(function(){var c={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:require("bean"),debug:!1,browser:{mobile:navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i)},addBlocks:function(){return function(d){d(DISQUS)}}};c.templateGlobals={urls:DISQUS.use("urls"),sso:null,_:{pluralize:_.pluralize}};c.renderBlock=function(d,a){return DISQUS.blocks[d](c.templateGlobals,a)};c.assureOffset=function(d){return d.indexOf("+")>=
0?d:d+"+00:00"};var f=c.Builder=function(){this.accum=[]};_.extend(f.prototype,{put:function(d){this.accum.push(d)},esc:function(d){return String(d).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});return c});
DISQUS.define("urls",function(){var c=encodeURIComponent(document.referrer),f={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1346444993",loading:"http://mediacdn.disqus.com/1346444993/html/simple-loading.html",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+c,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",
moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1346444993/images/noavatar92.png"}};window.location.protocol==="https:"&&(f=_.extend(f,{root:"",media:"",loading:"/html/simple-loading.html",realertime:f.realertime.replace("http://","https://"),api:f.apiSecure,logout:"https://disqus.com/logout/?redirect="+c,editProfile:"https://disqus.com/account/",
moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/images/noavatar92.png"}}));return f});
DISQUS.define("api",function(){function c(a){function g(b){var c=b.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,c.length)===c&&(b=DISQUS.JSON.parse(b.originalEvent.data),b.requestId==d&&(c=b.code===0?a.success:a.error,delete b.requestId,(c||function(){})(b),document.body.removeChild(f),document.body.removeChild(e),$(window).unbind("message",g)))}var d=_.uniqueId(),b=document.createElement("div"),e=document.createElement("form"),c="frame_"+d,f;b.innerHTML='<iframe name="'+c+'"></iframe>';f=b.childNodes[0];
e.target=c;e.action=a.url.replace(".json",".pm");e.method=a.method||"GET";a.data=_.extend(a.data,{callback:d,referrer:document.referrer});_.each(a.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;e.appendChild(c)})});$(window).bind("message",g);document.body.appendChild(f);document.body.appendChild(e);e.submit()}function f(a){a=_.defaults(a,d);a.data=a.data||{};a.data.api_key=
DISQUS.apiKey;$.ajax(a)}var d={};return{defaults:function(a){_.extend(d,a)},getURL:function(a,c){c=c||{};if(c.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+a;return DISQUS.urls.api+a},ajax:f,call:function(a,d){d=d||{};d.url=DISQUS.api.getURL(a,{secure:d.secure});d.data=_.extend(d.data||{},{api_key:DISQUS.apiKey});(d.secure?c:f)(d)}}});
(function(c){var f=DISQUS.Bus,d=DISQUS.api.getURL("internal/switches/list.jsonp");c.switches_jsonp_cb=function(a){f.sendHostMessage("switches.received",a.response)};f.on("fetch",function(a){a=a||{};a.data=a.data||{};a.data.callback="switches_jsonp_cb";a.data.api_key=DISQUS.apiKey;a=DISQUS.serialize(d,a.data,!1);DISQUS.require(a)});f.sendHostMessage("ready")})(this);