var DISQUS=function(d){var g={AssertionError:function(c){this.message=c}};g.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};g.assert=function(c,d){if(!c)throw new g.AssertionError(d);};var l=[];g.define=function(c,j){typeof c==="function"&&(j=c,c="");for(var b=c.split("."),a=b.shift(),f=g,n=(j||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},d);a;)f=f[a]?f[a]:f[a]={},a=b.shift();for(var m in n)n.hasOwnProperty(m)&&
(n.__overwrites__||f[m]!==null&&g.assert(!f.hasOwnProperty(m),"Unsafe attempt to redefine existing module with "+m),f[m]=n[m],l.push(function(a,b){return function(){delete a[b]}}(f,m)));return f};g.use=function(c){return g.define(c)};g.cleanup=function(){for(var c=0;c<l.length;c++)l[c]()};return g}(this);
DISQUS.define(function(d,g){var l=d.document,c=l.getElementsByTagName("head")[0]||l.body,j={running:!1,timer:null,queue:[]};DISQUS.defer=function(b,a){function f(){var a=j.queue;if(a.length===0)j.running=!1,clearInterval(j.timer);for(var b=0,f;f=a[b];b++)f[0]()&&(a.splice(b--,1),f[1]())}j.queue.push([b,a]);f();if(!j.running)j.running=!0,j.timer=setInterval(f,100)};DISQUS.each=function(b,a){var f=b.length,c=Array.prototype.forEach;if(isNaN(f))for(var m in b)b.hasOwnProperty(m)&&a(b[m],m,b);else if(c)c.call(b,
a);else for(c=0;c<f;c++)a(b[c],c,b)};DISQUS.extend=function(b){DISQUS.each(Array.prototype.slice.call(arguments,1),function(a){for(var f in a)b[f]=a[f]});return b};DISQUS.serializeArgs=function(b){var a=[];DISQUS.each(b,function(b,c){b!==g&&a.push(c+(b!==null?"="+encodeURIComponent(b):""))});return a.join("&")};DISQUS.isString=function(b){return Object.prototype.toString.call(b)==="[object String]"};DISQUS.serialize=function(b,a,c){a&&(b+=~b.indexOf("?")?b.charAt(b.length-1)=="&"?"":"&":"?",b+=DISQUS.serializeArgs(a));
if(c)return a={},a[(new Date).getTime()]=null,DISQUS.serialize(b,a);a=b.length;return b.charAt(a-1)=="&"?b.slice(0,a-1):b};DISQUS.require=function(b,a,f,d,m){function g(e){if(e.type=="load"||/^(complete|loaded)$/.test(e.target.readyState))d&&d(),p&&clearTimeout(p),DISQUS.bean.remove(e.target,j,g)}var h=l.createElement("script"),j=h.addEventListener?"load":"readystatechange",p=null;h.src=DISQUS.serialize(b,a,f);h.async=!0;h.charset="UTF-8";(d||m)&&DISQUS.bean.add(h,j,g);m&&(p=setTimeout(function(){m()},
2E4));c.appendChild(h);return DISQUS};DISQUS.requireStylesheet=function(b,a,f){var d=l.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=DISQUS.serialize(b,a,f);c.appendChild(d);return DISQUS};DISQUS.requireSet=function(b,a,c){var d=b.length;DISQUS.each(b,function(b){DISQUS.require(b,{},a,function(){--d===0&&c()})})};DISQUS.injectCss=function(b){var a=l.createElement("style");a.setAttribute("type","text/css");b=b.replace(/\}/g,"}\n");d.location.href.match(/^https/)&&(b=b.replace(/http:\/\//g,
"https://"));a.styleSheet?a.styleSheet.cssText=b:a.appendChild(l.createTextNode(b));c.appendChild(a)}});
DISQUS.define("JSON",function(){function d(e){return e<10?"0"+e:e}function g(e){a.lastIndex=0;return a.test(e)?'"'+e.replace(a,function(e){var a=m[e];return typeof a==="string"?a:"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+e+'"'}function l(e,a){var b,c,d,m,h=f,r,i=a[e];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!j&&(i=i.toJSON(e));typeof o==="function"&&(i=o.call(a,e,i));switch(typeof i){case "string":return g(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";f+=n;r=[];if(Object.prototype.toString.apply(i)==="[object Array]"){m=i.length;for(b=0;b<m;b+=1)r[b]=l(b,i)||"null";d=r.length===0?"[]":f?"[\n"+f+r.join(",\n"+f)+"\n"+h+"]":"["+r.join(",")+"]";f=h;return d}if(o&&typeof o==="object"){m=o.length;for(b=0;b<m;b+=1)c=o[b],typeof c==="string"&&(d=l(c,i))&&r.push(g(c)+(f?": ":":")+d)}else for(c in i)Object.hasOwnProperty.call(i,c)&&(d=l(c,i))&&r.push(g(c)+(f?": ":":")+d);d=r.length===0?"{}":f?"{\n"+f+r.join(",\n"+f)+"\n"+
h+"}":"{"+r.join(",")+"}";f=h;return d}}var c={},j=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,n,m={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;c.stringify=function(e,b,a){var c;n=f="";if(typeof a==="number")for(c=0;c<a;c+=1)n+=" ";else typeof a==="string"&&(n=a);if((o=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return l("",{"":e})};c.parse=function(e,a){function c(e,
b){var d,f,i=e[b];if(i&&typeof i==="object")for(d in i)Object.hasOwnProperty.call(i,d)&&(f=c(i,d),f!==void 0?i[d]=f:delete i[d]);return a.call(e,b,i)}var d,e=String(e);b.lastIndex=0;b.test(e)&&(e=e.replace(b,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(e.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+e+")"),
typeof a==="function"?c({"":d},""):d;throw new SyntaxError("JSON.parse");};var h={a:[1,2,3]},q,p;if(Object.toJSON&&Object.toJSON(h).replace(/\s/g,"")==='{"a":[1,2,3]}')q=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(h='{"a":[1,2,3]}'.evalJSON(),h.a&&h.a.length===3&&h.a[2]===3&&(p=function(e){return e.evalJSON()}));(function(){var e=[1,2,3];typeof e.toJSON==="function"&&(e=e.toJSON(),j=!(e&&e.length===3&&e[2]===3))})();if(j||!q||!p)return{stringify:c.stringify,parse:c.parse};return{stringify:q,
parse:p}});
DISQUS.define(function(){function d(b){for(a=1;b=g.shift();)b()}var g=[],l,c=document,j=c.documentElement,b=j.doScroll,a=/^loade|c/.test(c.readyState),f;c.addEventListener&&c.addEventListener("DOMContentLoaded",l=function(){c.removeEventListener("DOMContentLoaded",l,!1);d()},!1);b&&c.attachEvent("onreadystatechange",l=function(){/^c/.test(c.readyState)&&(c.detachEvent("onreadystatechange",l),d())});f=b?function(b){self!=top?a?b():g.push(b):function(){try{j.doScroll("left")}catch(a){return setTimeout(function(){f(b)},50)}b()}()}:
function(b){a?b():g.push(b)};return{domready:f}});
DISQUS.define("Events",function(){var d=/\s+/,g={on:function(g,c,j){var b,a;if(!c)return this;g=g.split(d);for(b=this._callbacks||(this._callbacks={});a=g.shift();)a=b[a]||(b[a]=[]),a.push(c),a.push(j);return this},off:function(g,c,j){var b,a,f;if(!(a=this._callbacks))return this;if(!g&&!c&&!j)return delete this._callbacks,this;for(g=g?g.split(d):_.keys(a);b=g.shift();)if(!(f=a[b])||!c&&!j)delete a[b];else for(b=f.length-2;b>=0;b-=2)c&&f[b]!==c||j&&f[b+1]!==j||f.splice(b,2);return this},trigger:function(g){var c,
j,b,a,f,n,m;if(!(j=this._callbacks))return this;m=[];g=g.split(d);a=1;for(f=arguments.length;a<f;a++)m[a-1]=arguments[a];for(;c=g.shift();){if(n=j.all)n=n.slice();if(b=j[c])b=b.slice();if(b){a=0;for(f=b.length;a<f;a+=2)b[a].apply(b[a+1]||this,m)}if(n){c=[c].concat(m);a=0;for(f=n.length;a<f;a+=2)n[a].apply(n[a+1]||this,c)}}return this}};g.bind=g.on;g.unbind=g.off;return g});
DISQUS.define(function(d,g){function l(){throw Error(Array.prototype.join.call(arguments," "));}function c(e,b,a){if(e.addEventListener)e.addEventListener(b,a,!1);else if(e.attachEvent)e.attachEvent("on"+b,a);else throw Error("No event support.");}var j=d.document,b=DISQUS.use("JSON");if(!(DISQUS!==g&&DISQUS.version&&DISQUS.version()=="__version__")){var a={},f={},n=0;c(d,"message",function(e){var a,c;for(c in f)if(Object.prototype.hasOwnProperty.call(f,c)&&e.origin==f[c].origin){a=!0;break}if(a)switch(a=
b.parse(e.data),(c=f[a.sender])||l("Message from our server but with invalid sender UID:",a.sender),a.scope){case "host":c.trigger(a.name,a.data);break;case "global":DISQUS.trigger(a.name,a.data);break;default:l("Message",a.scope,"not supported. Sender:",e.origin)}},!1);c(d,"hashchange",function(){DISQUS.trigger("window.hashchange",{hash:d.location.hash})},!1);c(d,"resize",function(){DISQUS.trigger("window.resize")},!1);var m=function(){DISQUS.trigger("window.scroll")};(function(e,a,b,d){var g=(new Date).getTime();
c(e,a,function(){var e=(new Date).getTime();e-g>=d&&(g=e,b())})})(d,"scroll",m,250);(function(e,a,b,d){var g;c(e,a,function(e){g&&clearTimeout(g);g=setTimeout(function(){b(e)},d)})})(d,"scroll",m,300);c(j,"click",function(){DISQUS.trigger("window.click")});m=function(){this.uid=n++;a[this.uid]=this};DISQUS.extend(m.prototype,DISQUS.Events);m.prototype.destroy=function(){delete a[this.uid]};DISQUS.extend(m,{listByKey:function(){var e={},b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&(e[b]=
a[b]);return e},list:function(){var e=[],b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&e.push(a[b]);return e},get:function(e){if(Object.prototype.hasOwnProperty.call(a,e))return a[e];return null}});var o=function(e){e=e||{};this.isReady=!1;this.uid=e.uid||n++;this.elem=null;this.styles={};this.role=e.role||"application"};o.prototype.load=function(){var e=this.elem=j.createElement("iframe");e.setAttribute("id","dsq"+this.uid);e.setAttribute("data-disqus-uid",this.uid);e.setAttribute("allowTransparency",
"true");e.setAttribute("frameBorder","0");e.setAttribute("role",this.role);for(var b in this.styles)this.styles.hasOwnProperty(b)&&(e.style[b]=this.styles[b])};o.prototype.destroy=function(){this.elem&&this.elem.parentNode.removeChild(this.elem)};var h=function(b){var a=this;o.call(a,b);a.listeners={};a.origin=b.origin;a.target=b.target;a.container=b.container;a.styles={width:"100%",border:"none",overflow:"hidden",display:"none"};f[a.uid]=a;a.on("ready",function(){a.isReady=!0})};DISQUS.extend(h.prototype,
DISQUS.Events);h.prototype.load=function(b){o.prototype.load.call(this);var a=this.elem;a.setAttribute("width","100%");a.setAttribute("src",this.target+"#"+this.uid);c(a,"load",function(){a.style.display="";b&&b()});(j.getElementById(this.container)||j.body).appendChild(a);this.elem=a};h.prototype.sendMessage=function(a,c){var d=function(a,b,e){return function(){e.elem.contentWindow.postMessage(a,b)}}(b.stringify({scope:"client",data:{eventName:a,data:c}}),this.origin,this);if(this.isReady)d();else this.on("ready",
d)};h.prototype.getPosition=function(){for(var a=this.elem,b=0,c=0;a;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{top:c,left:b}};h.prototype.inViewport=function(a){var a=a||this.getPosition(),a=a.top,b=a+this.elem.offsetHeight,c=d.pageYOffset;return!(a>c+d.innerHeight||b<c)};h.prototype.destroy=function(){this.off();o.prototype.destroy.call(this)};var q=function(a){o.call(this,a);this.contents=a.contents;this.container=a.container;this.styles={width:"100%",border:"none",overflow:"hidden"};
a.styles=a.styles||{};for(var b in a.styles)a.styles.hasOwnProperty(b)&&(this.styles[b]=a.styles[b])};q.prototype.load=function(){o.prototype.load.call(this);var a=this.elem;a.setAttribute("scrolling","no");(j.getElementById(this.container)||j.body).appendChild(a);this.element=a;this.window=a.contentWindow;try{this.window.document.open()}catch(b){a.src="javascript:var d=document.open();d.domain='"+j.domain+"';void(0);"}this.document=this.window.document;this.document.write(this.contents);this.document.close();
if(a=this.document.body)this.element.style.height=a.offsetHeight+"px"};q.prototype.exec=function(a){a.call(this,this.window,this.document)};q.prototype.hide=function(){var a=this.element.style.display;if(a!=="none")this._display=a;this.element.style.display="none"};q.prototype.show=function(){this.element.style.display=this._display||"block"};q.prototype.click=function(a){c(this.document.body,"click",function(b){a(b)})};q.prototype.destroy=o.prototype.destroy;var p=DISQUS.extend({},DISQUS.Events);
return{IFRAME:"__widget_iframe__",log:function(a){var b=j.getElementById("messages");if(b){var c=j.createElement("p");c.innerHTML=a;b.appendChild(c)}},version:function(){return"__version__"},on:p.on,off:p.off,trigger:p.trigger,Channel:h,Sandbox:q,App:m}}});
DISQUS.define(function(){function d(d){DISQUS.App.call(this);this.switches={};var l={target:d.useSSL?"https://securecdn.disqus.com/1346444993/build/next-switches/client_ssl.html":"http://mediacdn.disqus.com/1346444993/build/next-switches/client.html",container:d.container};l.origin=d.useSSL?"https://securecdn.disqus.com":"http://mediacdn.disqus.com";this.frame=new DISQUS.Channel(l);var c=this;this.frame.load(function(){c.frame.elem.style.display="none"})}d.prototype=DISQUS.extend({fetch:function(d){var l=
this,d=d||{},c=d.success;delete d.success;this.frame.on("switches.received",function(d){l.switches=d;DISQUS.trigger("switches.changed",d);c&&c(d)});this.frame.sendMessage("fetch",d)},enabled:function(d){return this.switches[d]?this.switches[d]:!1}},DISQUS.App.prototype);return{Switches:function(g){return new d(g)}}});
DISQUS.define(function(d,g){function l(a,b,d,c,f,e){return'<img width="'+a+'" height="'+b+'" alt="'+c+'" src="data:image/'+d+";base64,"+f+'"'+(e?'style="'+e+'"':"")+"/>"}function c(a){for(var b=DISQUS.App.list(),d=0,c=b.length,b=b[d];d<c;d++)b instanceof f&&a(b)}var j=d.document,b=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG",
"MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN","+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP","lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU",
"FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P","mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A","I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg",
"wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU","ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo","HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91",
"WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV","lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm","gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB",
"mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF","TkSuQmCC"],a=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth",
"LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh","+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+","YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7",
"AAAAAAAAAAAA"],f=function(a){DISQUS.App.call(this);this.settings=a;this.indicators={north:null,south:null};this._boundGlobalEvents=[];this.frame=null};DISQUS.extend(f.prototype,DISQUS.App.prototype);f.prototype.init=function(){function c(a,b){f._boundGlobalEvents.push(a);DISQUS.on(a,b,f)}var f=this,h=f.settings,n="http://disqus.com/embed/comments/",p="http://disqus.com";h.useSSL&&(n="https://disqus.com/embed/comments/",p="https://disqus.com");var e={f:h.forum,t_i:h.identifier,t_u:h.url||d.location.href,
t_s:h.slug,t_t:h.title,s_o:h.sortOrder,c:h.useConman||g};if(h.notSupported)e.n_s=1;var v=DISQUS.isString(h.container)?j.getElementById(h.container):h.container,k=f.frame=new DISQUS.Channel({origin:p,target:DISQUS.serialize(n,e),container:h.container,uid:this.uid});if(h.notSupported)k.styles.height="500px";var t=!1,u,s;if(!h.notSupported)u=j.createElement("div"),u.innerHTML=l(71,17,"png","DISQUS",b.join(""))+l(16,11,"gif","...",a.join(""),"margin:0 0 3px 5px"),v.appendChild(u);n=function(){var a=k.getPosition(),
b=d.pageYOffset,c=d.innerHeight,f=k.inViewport(a);f?(t=!0,k.sendMessage("window.scroll",{frameOffset:a,pageOffset:b,height:c}),k.sendMessage("window.inViewport")):t&&!f&&(t=!1,k.sendMessage("window.scrollOffViewport"))};k.on("ready",function r(a){k.off("ready",r);u&&u.parentNode===v&&v.removeChild(u);d.clearTimeout(s);var b={themeUrl:h.themeUrl,permalink:h.permalink,anchorColor:h.anchorColor,referrer:d.location.href,colorScheme:h.colorScheme,serif:h.serif,remoteAuthS3:h.remoteAuthS3,apiKey:h.apiKey,
sso:h.sso,parentWindowHash:d.location.hash};if(d.navigator.userAgent.match(/(iPad|iPhone|iPod)/))b.width=k.elem.offsetWidth;k.inViewport()&&k.sendMessage("window.inViewport");f.clientData=a;k.sendMessage("init",b);f.trigger("loading.init")});k.on("resize",function(a){k.elem.style.height=a.height+"px"});k.on("reload",function(){d.location.reload()});k.on("reset",function(){DISQUS.reset({reload:!0})});k.on("posts.paginate",function(){f.trigger("posts.paginate")});k.on("posts.create",function(a){f.trigger("posts.create",
{id:a.id,text:a.raw_message})});k.on("scrollTo",function(a){var b=k.getPosition(),b=a.relative==="window"?a.top:b.top+a.top;(a.force||!(b>d.pageYOffset&&b<d.pageYOffset+d.innerHeight))&&d.scrollTo(0,b)});k.on("fakeScroll",n);k.on("realtime.init",function(a){for(var b=["north","south"],c,d,e=0;e<b.length;e++)d=b[e],c=new DISQUS.Sandbox({uid:"-indicator-"+d,container:f.settings.container,contents:a[d].contents,styles:a[d].styles}),c.load(),c.hide(),function(a){c.click(function(){k.sendMessage("realtime.click",
a)})}(d),f.indicators[d]=c});k.on("realtime.showNorth",function(a){var b=f.indicators.north;b.document.getElementById("message").innerHTML=a;b.show()});k.on("realtime.hideNorth",function(){f.indicators.north.hide()});k.on("realtime.showSouth",function(a){var b=f.indicators.south;b.document.getElementById("message").innerHTML=a;b.show()});k.on("realtime.hideSouth",function(){f.indicators.south.hide()});k.on("mainViewRendered",function(){DISQUS.trigger("lounge:mainViewRendered");f.trigger("loading.done")});
s=d.setTimeout(function(){u.innerHTML+='<p>DISQUS seems to be taking longer than usual. <a href="#" onclick="DISQUS.reset({reload: true}); return false;">Reload</a>?</p>'},1E4);k.load(function(){h.notSupported?(k.elem.setAttribute("height","500px"),k.elem.setAttribute("scrolling","yes"),k.elem.setAttribute("horizontalscrolling","no"),k.elem.setAttribute("verticalscrolling","yes")):(k.elem.setAttribute("scrolling","no"),k.elem.setAttribute("horizontalscrolling","no"),k.elem.setAttribute("verticalscrolling",
"no"))});c("window.hashchange",function(a){k.sendMessage("window.hashchange",a.hash)});c("window.resize",function(){k.sendMessage("window.resize")});c("window.scroll",n);c("window.click",function(){k.sendMessage("window.click")});c("switches.changed",function(a){k.sendMessage("switches.changed",a)});f.trigger("loading.start")};f.prototype.destroy=function(){var a=this.indicators;this.off();if(this._boundGlobalEvents.length)DISQUS.off(this._boundGlobalEvents.join(" "),null,this),this._boundGlobalEvents=
null;this.frame&&this.frame.destroy();if(a.north)a.north.destroy(),a.north=null;if(a.south)a.south.destroy(),a.south=null;DISQUS.App.prototype.destroy.call(this)};var n=function(a){return new f(a)};DISQUS.extend(n,{listByKey:function(){var a={};c(function(b){a[b.uid]=b});return a},list:function(){var a=[];c(function(b){a.push(b)});return a},get:function(a){a=DISQUS.App.get(a);return a instanceof f&&a}});return{Lounge:n}});
(function(d,g,l){function c(){function a(b){var b=b.getAttribute?b.getAttribute("src"):b.src,c=[/(https?:)\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/(https?:)\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/(https?:)\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/(https?:)\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var f=0;f<d;f++){var i=b.match(c[f]);if(i&&i.length&&i.length==4)return e=i[1]||null,i[3]}return null}for(var b=g.getElementsByTagName("script"),
c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==null)return d}return null}function j(){if(d.location.protocol==="https:")return!0;e===l&&c();return e==="https:"}function b(a,c,f){var e;if(a===g)return"";d.getComputedStyle?e=g.defaultView.getComputedStyle(a,null).getPropertyValue(c):a.currentStyle&&(e=a.currentStyle[c]?a.currentStyle[c]:a.currentStyle[f]);return e=="transparent"||e===""||e=="rgba(0, 0, 0, 0)"?b(a.parentNode,c,f):e||null}function a(a){a.match("^rgb")&&(a=f(a).substr(1));var b=parseInt(a.substr(0,
2),16),c=parseInt(a.substr(2,2),16),a=parseInt(a.substr(4,2),16);return(b*299+c*587+a*114)/1E3}function f(a){function b(a){a=Number(a).toString(16);return a.length==1?"0"+a:a}if(a.substr(0,1)==="#")return a;var c=/.*?rgb\((\d+),\s*(\d+),\s*(\d+)\)/.exec(a);if(!c||c.length!==4)return"";var a=b(c[1]),d=b(c[2]),c=b(c[3]);return"#"+a+d+c}function n(a,c,d){DISQUS.isString(a)&&(a=g.createElement(a));var f=null;a.style.visibility="hidden";p.appendChild(a);f=b(a,c,d);p.removeChild(a);return f}function m(){var a=
g.createElement("a");a.href=+new Date;return n(a,"color")}function o(){for(var a=g.getElementsByTagName("h1"),b=g.title,c=b.length,d=b,f=0.6,e=0;e<a.length;e++)(function(a){var a=a.textContent||a.innerText,e;if(!(a===null||a===l)){e=0;for(var g=Array(b.length),i=0;i<=b.length;i++){g[i]=Array(a.length);for(var h=0;h<=a.length;h++)g[i][h]=0}for(i=0;i<b.length;i++)for(h=0;h<a.length;h++)b[i]==a[h]&&(g[i+1][h+1]=g[i][h]+1,g[i+1][h+1]>e&&(e=g[i+1][h+1]));e/=c;e>f&&(f=e,d=a)}})(a[e]);return d}function h(){g.getElementById(q).innerHTML=
"";var b=k.page;if(!d.postMessage||!d.JSON)w=!0;if(d.navigator.appName==="Microsoft Internet Explorer"&&(!g.documentMode||g.documentMode<8))w=!0;b={container:q,forum:t,anchorColor:m(),colorScheme:128<a(n("span","color"))?"dark":"light",sortOrder:"popular",permalink:v,serif:{courier:1,times:1,georgia:1,palatino:1}.hasOwnProperty(n("span","font-family","fontFamily").toLowerCase()),useSSL:j(),url:b.url||d.location.href.replace(/#.*$/,""),title:b.title||o(),slug:b.slug,category:b.category_id,identifier:b.identifier,
apiKey:b.api_key,remoteAuthS3:b.remote_auth_s3,sso:k.sso,themeUrl:d.disqus_theme_root_url,useConman:d.disqus_demo,notSupported:w};s=DISQUS.Lounge(b);var c={onReady:"loading.done",onNewComment:"posts.create",onPaginate:"posts.paginate"};DISQUS.each(k.callbacks,function(a,b){c[b]&&DISQUS.each(a,function(a){s.on(c[b],a)})});s.init()}var q=d.disqus_container_id||"disqus_thread",p=g.getElementById(q),e,v=function(){var a=d.location.hash;return(a=a&&a.match(/comment\-([0-9]+)/))&&a[1]}(),k={page:{url:l,
title:l,slug:l,category_id:l,identifier:l,api_key:l,remote_auth_s3:l,author_s3:l,developer:l},sso:{},callbacks:{preData:[],preInit:[],onInit:[],afterRender:[],onReady:[],onNewComment:[],preReset:[],onPaginate:[]}};DISQUS.each(["developer","shortname","identifier","url","title","category_id","slug"],function(a){var b=d["disqus_"+a];typeof b!=="undefined"&&(k.page[a]=b)});var t=d.disqus_shortname||c(),t=t.toLowerCase();if(typeof d.disqus_config==="function")try{d.disqus_config.call(k)}catch(u){}var s,
w=!1;h();if(!w){var r=DISQUS.Switches({container:q,useSSL:j()});r.fetch({data:{forum:t}});DISQUS.domready(function(){if(g.getElementsByClassName){var a=g.getElementsByClassName("dsq-brlink");a&&a.length&&a[0].parentNode.removeChild(a[0])}});DISQUS.request={get:function(a,b,c){DISQUS.require(a,b,c)}};DISQUS.reset=function(a){a=a||{};if(typeof a.config==="function")try{a.config.call(k)}catch(b){}s&&(s.destroy(),s=null);a.reload&&(h(),DISQUS.trigger("switches.changed",r.switches))}}})(this,this.document);