DISQUS.addBlocks("theme")(function(g){g.blocks.relatedThread=function(c,d){var b=new g.Builder,a=DISQUS.extend({},c,d);with(a)return b.put('    <li class="discovery-unit">        <h3 title="'),b.put(thread.title),b.put('"><span class="publisher-anchor-color"><a class="title" href="'),b.put((b.esc||function(a){return a})(thread.link)),b.put('#disqus_thread" data-redirect="'),b.put((b.esc||function(a){return a})(thread.redirectUrl)),b.put('">'),b.put(thread.title),b.put('</a></span></h3>        <ul class="meta">            <li class="likes"><span class="votes">Up votes</span>'),
b.put((b.esc||function(a){return a})(thread.likes)),b.put('</li>            <li class="comments">                <a href="#">                '),thread.posts==1?b.put("                    1 comment                "):thread.posts>=0&&(b.put("                    "),b.put((b.esc||function(a){return a})(thread.posts)),b.put(" comments                ")),b.put('                </a>            </li>            <li class="time">'),b.put((b.esc||function(a){return a})(thread.createdAgo)),b.put('</li>        </ul>        <a class="top-comment" href="'),
b.put((b.esc||function(a){return a})(thread.link)),b.put('#disqus_thread" data-redirect="'),b.put((b.esc||function(a){return a})(thread.redirectUrl)),b.put('" data-role="discovery-top-comment">            <img src="'),b.put((b.esc||function(a){return a})(urls.avatar.generic)),b.put('" alt="Default user" data-role="discovery-avatar">            <p><span class="user" data-role="discovery-top-comment-author">'),b.put('</span> &#8212; <span data-role="discovery-top-comment-snippet">'),b.put("</span></p>        </a>    </li>"),
b.compile()};g.blocks.relatedThreads=function(c,d){var b=new g.Builder,a=DISQUS.extend({},c,d);with(a)return b.put('<div id="discovery-main">    <div id="discovery-note" style="display:none;">        <div class="alert">            The new DISQUS Discovery box helps you find other vibrant discussions on the communities you love. Feedback? <a href="https://www.surveymonkey.com/s/GHK872T" target="_blank">Let us know.</a>        </div>    </div>    <header>        <div id="discovery-options">            <span class="publisher-anchor-color"><a href="#" id="discovery-help" data-action="discovery-help">What\'s this?</a></span>            <a href="#" id="discovery-close" data-action="discovery-close" title="Close this box">\u00d7</a>        </div>        <h2>Also on '),
b.put((b.esc||function(a){return a})(forum.name)),b.put('</h2>    </header>    <section>        <ul id="discovery-units">            '),b.put("        </ul>    </section></div>"),b.compile()}});
(function(g){var c=g.DISQUS;c.registerActions=function(){c.define("discovery.views",function(){return{load:function(){var d=c.discovery.views,b=d.RelatedThreadView=Backbone.View.extend({events:{"click [data-redirect]":"swapLink"},dtplBlock:"relatedThread",initialize:function(a){this.snippetLimit=a.snippetLimit;this.model.on("fetchedTopComment",function(a){this.renderTopComment(a)},this)},swapLink:function(a){a=a.target||a.srcElement;a.tagName.toUpperCase()=="A"&&a.getAttribute("data-redirect")||(a=
$(a).closest("a[data-redirect]")[0]);var b=a;b.setAttribute("data-href",b.getAttribute("href"));b.setAttribute("href",b.getAttribute("data-redirect"));_.delay(function(){b.setAttribute("href",b.getAttribute("data-href"))},100)},renderAvatar:function(a){var b=this.$el.find("[data-role=discovery-avatar]");b.attr("src",a.avatar.cache);b.attr("alt",this.authorName(a));return this},authorName:function(a){return a.name||a.username},renderCommentSnippet:function(a){var b=this.$el.find("[data-role=discovery-top-comment]");
if(a.author){var c=this.authorName(a.author);b.find("[data-role=discovery-top-comment-author]").text(c)}a=_.strip(a.message);a=_.truncate(a,this.snippetLimit);b.find("[data-role=discovery-top-comment-snippet]").text(a);b.css({display:"block"});return this},renderTopComment:function(a){this.renderAvatar(a.author);this.renderCommentSnippet(a);this.trigger("resize");return this},render:function(){this.setElement(c.renderBlock(this.dtplBlock,{thread:_(this.model.toJSON()).extend({createdAgo:moment(c.assureOffset(this.model.get("createdAt")),
c.ISO_8601).fromNow()})}));return this}});d.RelatedThreadCollectionView=Backbone.View.extend({events:{"click [data-action=discovery-close]":"close","click [data-action=discovery-help]":"showHelp"},dtplBlock:"relatedThreads",initialize:function(a){this.snippetLimit=a.snippetLimit},close:function(a){a.preventDefault();this.remove();this.trigger("resize",0)},showHelp:function(a){a.preventDefault();$(a.currentTarget).hide();this.$el.find("#discovery-note").show();this.trigger("resize")},getTopComment:function(a){var b=
this;c.api.call("discovery/listTopPost.json",{method:"GET",data:{thread:a},success:function(a){a.response.length!==0&&_.each(a.response,function(a){b.collection.get(a.thread).trigger("fetchedTopComment",a)})}});return b},resize:_.debounce(function(){this.trigger("resize")},500),render:function(){this.setElement(c.renderBlock(this.dtplBlock,{forum:this.collection.mainThread.get("forum")}));this.collection.each(function(a){a=new b({model:a,snippetLimit:this.snippetLimit});a.on("resize",this.resize,
this);a.render();this.$el.find("section > ul").append(a.el)},this);this.getTopComment(this.collection.pluck("id"));return this}});return d}}});c.define("discovery.collections",function(){return{load:function(d,b){var a=c.discovery.collections;a.RelatedThreadCollection=Backbone.Collection.extend({model:d.RelatedThread,url:function(){return!c.debug?c.api.getURL("discovery/listRelated.json"):c.api.getURL("threads/list.json")},initialize:function(a,b){this.mainThread=b.thread;this.limit=b.limit;this.variant=
b.variant;this.impId=(new Date).getTime().toString(10)+Math.floor(Math.random()*1E6).toString(10)},fetch:function(a){var b={};b.data=!c.debug?{thread:this.mainThread.get("id")}:{forum:this.mainThread.get("forum").id};b.parse=!1;_.extend(b,a);Backbone.Collection.prototype.fetch.call(this,b)},parse:function(a){var d=[],e=a.response;b.log("Results (",e.length,"):",e);for(var f=0,g=e.length;f<g&&d.length<this.limit;f++)if(a=e[f].thread||e[f],a.id!=this.mainThread.id)a.posts===0?b.log("Thread",a.id,"does not have any comments."):
a.title.indexOf("http://")===0?b.log("Thread",a.id,"has a title that starts with http."):(a.redirectUrl=c.serialize(e[f].signedUrl?"http://redirect.disqus.com/url":a.link+"#redirect",{url:e[f].signedUrl,thread:a.id,forum:a.forum,zone:"internal_discovery",variant:this.variant,imp:this.impId,source_thread_id:this.mainThread.id}),a.score={score:e[f].score,k:e[f].k},d.push(a));b.log("Total results:",d.length);return d}});return a}}});c.define("discovery.models",function(){return{load:function(){var d=
c.discovery.models,b=d.Thread=Backbone.Model.extend({defaults:{author:null,category:null,createdAt:null,forum:null,identifiers:[],ipAddress:null,isClosed:!1,isDeleted:!1,link:null,message:null,slug:null,title:null,userSubscription:!1,posts:0,reactions:0,likes:0,dislikes:0,userScore:0},url:c.api.getURL("threads/details"),parse:function(a){return a.response}});d.RelatedThread=b.extend({defaults:_.extend({},b.prototype.defaults,{redirectUrl:null})});return d}}});c.define("discovery.utils",function(c,
b){var a=!1;return{allowLog:function(c){if(c===b)return a;a=!!c},log:function(){if(!c.console)return function(){};return function(){a&&(c.console.log.apply?c.console.log.apply(c.console,arguments):c.console.log(_.toArray(arguments).join(" ")))}}()}});c.define("discovery",function(){return this.overwrites({init:function(d,b){function a(a){f("discovery_next:dark_promoted",function(){j.log("Initiating dark request to discovery/listPromoted");c.api.call("discovery/listPromoted.json",{data:{thread:d.thread.id}})});
k=new n(null,{thread:a,limit:m,variant:d.variant});k.fetch({success:g,error:i});k.on("error",i)}function g(a){if(a.length<2)return void i({display:!1});a=new o({id:"discovery",collection:a,snippetLimit:p});b(a);i({display:!0})}function i(a){a=a||{};l||(l=!0,c.juggler&&(a={major_version:"next_internal",variant:d.variant,internal_organic:k.length,external_organic:0,promoted:0,display:!!a.display},j.log("Juggler init_discovery",a),c.juggler.emit("init_discovery",a)))}var e=d.switches,f=function(a,b,
c){if(e)if(e.length)e.enabled(a)&&b();else{var d=function(){e.enabled(a)&&b();c&&e.off("reset",d)};return void e.on("reset",d)}};f("discovery_next:logging",function(){c.discovery.utils.allowLog(!0)});var m=d.variant=="top2"?2:4,p=100,j=c.discovery.utils,h=c.discovery.models.load(),q=c.discovery.collections.load(h,j),r=c.discovery.views.load(),h=h.Thread,n=q.RelatedThreadCollection,o=r.RelatedThreadCollectionView,k;d.threadId?(j.log("Discovery: Making call to threads/details"),(new h).fetch({data:{thread:d.threadId,
forum:d.forum,related:"forum"},success:a})):a(new h(_.extend(d.thread,{forum:d.forum})));var l=!1}})})};c.runThemeScript=c.registerActions})(this);